# Generated by Django 5.2.11 on 2026-02-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleprogram',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sampleprogram',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
