# Generated by Django 5.2.11 on 2026-03-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonprogram',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='packed_pb_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='packed_pb_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='packed_pb_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='pcs_per_set',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gussetprogram',
            name='expected_date_confirmation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gussetprogram',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gussetprogram',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
