# Generated by Django 5.2.11 on 2026-02-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_sampleprogram_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='net_wt_pdq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
