# Generated by Django 5.2.11 on 2026-02-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_cartonprogramsubprogram_net_wt_pdq'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonprogram',
            name='program_type',
            field=models.CharField(choices=[('TOWEL', 'Towel'), ('BEDSHEET', 'Bedsheet'), ('TERRY TOWEL', 'Terry Towel'), ('BATH ROBE', 'Bath Robe')], default='TOWEL', max_length=50),
        ),
        migrations.CreateModel(
            name='BathRobeProgramDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_bath_robe', models.TextField(blank=True, null=True)),
                ('bath_robe_sizes', models.CharField(blank=True, max_length=200, null=True)),
                ('bath_robe_dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('bath_robe_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('folding_details', models.TextField(blank=True, null=True)),
                ('required_pcs_per_polybag', models.IntegerField(blank=True, null=True)),
                ('required_pcs_per_carton', models.IntegerField(blank=True, null=True)),
                ('polybag_type', models.CharField(blank=True, max_length=150, null=True)),
                ('polybag_size_carton', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('carton_program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathrobe_details', to='programs.cartonprogram')),
            ],
            options={
                'db_table': 'bath_robe_program_details',
            },
        ),
        migrations.CreateModel(
            name='BedsheetProgramDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_tc', models.CharField(blank=True, max_length=100, null=True)),
                ('folding_details', models.TextField(blank=True, null=True)),
                ('required_pcs_per_polybag', models.IntegerField(blank=True, null=True)),
                ('polybag_size', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(blank=True, max_length=150, null=True)),
                ('special_packing_requirement', models.CharField(blank=True, max_length=150, null=True)),
                ('packing_type', models.CharField(blank=True, max_length=150, null=True)),
                ('product_dimension', models.CharField(blank=True, max_length=200, null=True)),
                ('fold_size', models.CharField(blank=True, max_length=150, null=True)),
                ('blister_packing_required', models.BooleanField(default=False)),
                ('blister_packing_details', models.CharField(blank=True, max_length=150, null=True)),
                ('bag_type', models.CharField(blank=True, max_length=150, null=True)),
                ('special_box_required', models.CharField(blank=True, max_length=150, null=True)),
                ('required_sets_per_carton', models.IntegerField(blank=True, null=True)),
                ('polyfold_condition', models.CharField(blank=True, max_length=150, null=True)),
                ('filled_product_gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('carton_program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedsheet_details', to='programs.cartonprogram')),
            ],
            options={
                'db_table': 'bedsheet_program_details',
            },
        ),
        migrations.CreateModel(
            name='TerryTowelProgramDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towel_sizes', models.CharField(blank=True, max_length=200, null=True)),
                ('required_pcs_carton_size', models.CharField(blank=True, max_length=200, null=True)),
                ('required_polybags_carton_size', models.CharField(blank=True, max_length=200, null=True)),
                ('towel_dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('towel_weight_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('folding_details', models.TextField(blank=True, null=True)),
                ('required_pcs_per_polybag', models.IntegerField(blank=True, null=True)),
                ('special_carton_details', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('carton_program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terry_details', to='programs.cartonprogram')),
            ],
            options={
                'db_table': 'terry_towel_program_details',
            },
        ),
    ]
