# Generated by Django 5.2.11 on 2026-08-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_cartonprogram_remark_and_more'),
        ('programs', '0005_cartonprogram_program_type_bathrobeprogramdetails_and_more'),
    ]

    operations = [
    ]
