# Generated by Django 5.2.11 on 2026-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_merge_20260807_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonprogram',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='is_recalculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='last_recalculated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_cartons_per_20ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_cartons_per_40ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_cbm_per_carton',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_pallet_per_20ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_pallet_per_40ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_pdq_per_20ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_pdq_per_40ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartonprogramsubprogram',
            name='fold',
            field=models.CharField(max_length=500),
        ),
    ]
