# Generated by Django 5.2.11 on 2026-08-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_subprogram_size_uom_recalc_fields'),
        ('programs', '0007_cartonprogram_size_and_more'),
    ]

    operations = [
    ]
