# Generated by Django 5.2.11 on 2026-08-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_merge_20260807_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartonprogramsubprogram',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='cartonprogramsubprogram',
            name='self_fabric_bag',
        ),
        migrations.RemoveField(
            model_name='cartonprogramsubprogram',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cartonprogramsubprogram',
            name='weight_uom',
        ),
        migrations.AlterField(
            model_name='cartonprogramsubprogram',
            name='belly_band',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cartonprogramsubprogram',
            name='ribbon',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
