# Generated by Django 5.2.11 on 2026-04-28 08:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MARKETING', 'Marketing'), ('TTQM', 'TTQM'), ('PURCHASE', 'PURCHASE'), ('SUPER_ADMIN', 'Super Admin'), ('EMPLOYEE', 'Employee'), ('PPC', 'PPC'), ('WAREHOUSE', 'Warehouse'), ('TOP', 'Top'), ('TESTING', 'Testing'), ('LAB', 'LAB')], db_index=True, default='EMPLOYEE', max_length=20)),
                ('emp_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('allowed_pages', models.JSONField(blank=True, default=list, help_text='List of frontend page identifiers user can access')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'user',
                'indexes': [models.Index(fields=['role'], name='user_role_3744fd_idx'), models.Index(fields=['emp_code'], name='user_emp_cod_f86882_idx'), models.Index(fields=['company_name'], name='user_company_41a79a_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
