"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import configparser
from datetime import timedelta
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# EXTERNAL CONFIGURATION FILE LOADER
# Used to store:
# - Database credentials
# - Email credentials
# - Environment-specific values
# ============================================================

# Absolute path of external configuration file
# ../../cartonConf.ini means:
# Move two directories up from BASE_DIR and locate cartonConf.ini
CONFIG_FILE_PATH = os.path.join(BASE_DIR, "../../cartonConf.ini")
print("CONFIG_FILE_PATH----------------", CONFIG_FILE_PATH)

# Create config parser instance
config = configparser.ConfigParser()

# Read configuration file
config.read(CONFIG_FILE_PATH)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-omlrh&0x0(j4^nlvoqtztzp4n!9$d!+ly9hlkak^ijlf(xpnk1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.getboolean('settings', 'DEBUG')

ALLOWED_HOSTS = ['*']



AUTH_USER_MODEL = 'userManagement.User'


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    "corsheaders",

    "accounts",
    "userManagement",
    "programs",
    "activity_logs",
    "pp_sample",
    "labdip",
    "artwork",
    'saml_auth',
    
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Allow frontend to call backend
CORS_ALLOW_ALL_ORIGINS = True   # temporary for dev
# safer option:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # React dev server
# ]

CSRF_TRUSTED_ORIGINS = [
    "https://wll-welpulse.welspun.com",
    "https://login.microsoftonline.com"
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# ============================================================
# DATABASE CONFIGURATION (Microsoft SQL Server)
# ============================================================

# Database credentials loaded from configuration file / environment
DB_NAME = config.get("CartonDB", "DB_NAME")
DB_USER = config.get("CartonDB", "DB_USER")
DB_PSWD = config.get("CartonDB", "DB_PSWD")
DB_HOST = config.get("CartonDB", "DB_HOST")


# Django database settings
DATABASES = {
    "default": {

        # Backend engine for SQL Server
        # Requires: django-mssql-backend or django-pyodbc-azure
        "ENGINE": "mssql",

        # Database name
        "NAME": DB_NAME,

        # Database username
        "USER": DB_USER,

        # Database password
        "PASSWORD": DB_PSWD,

        # Database host (IP / hostname)
        "HOST": DB_HOST,

        # SQL Server default port
        # Leave empty to use driver default (1433)
        "PORT": "",

        # Extra driver-level options
        "OPTIONS": {

            # ODBC driver installed on system
            "driver": "ODBC Driver 17 for SQL Server",

        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# ============================================================
# STATIC FILES CONFIGURATION
# Used for:
# - CSS
# - JavaScript
# - Images bundled with frontend/admin
# ============================================================

# URL prefix used when referring to static files
# Example: /static/css/style.css
STATIC_URL = "/static/"

# Directory where all static files will be collected
# when running: python manage.py collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# ============================================================
# MEDIA FILES CONFIGURATION
# Used for:
# - User uploaded files
# - Profile pictures
# - Documents
# ============================================================

# URL prefix for uploaded media
# Example: /media/uploads/resume.pdf

MEDIA_URL = "/media/"

# Physical directory where uploaded files are stored
MEDIA_ROOT = BASE_DIR / "media"





# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# ============================================================
# EMAIL CONFIGURATION (SMTP)
# Used for:
# - Password reset emails
# - Notifications
# - System alerts
# ============================================================

# Use SMTP backend for sending real emails
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Alternative backend for local development:
# Prints email content to console instead of sending
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Email server host (example: smtp.gmail.com)
EMAIL_HOST = config.get("CartonMail", "EMAIL_HOST")

# Email server port (usually 587 for TLS, 465 for SSL)
EMAIL_PORT = config.getint("CartonMail", "EMAIL_PORT")

# Enable TLS encryption
EMAIL_USE_TLS = config.getboolean("CartonMail", "EMAIL_USE_TLS")

# Email account used to send mails
EMAIL_HOST_USER = config.get("CartonMail", "EMAIL_HOST_USER")

# Password or app-password for email account
EMAIL_HOST_PASSWORD = config.get("CartonMail", "EMAIL_HOST_PASSWORD")

# Default sender address
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# ============================================================
# DJANGO REST FRAMEWORK (DRF) CONFIGURATION
# Controls authentication, permissions, and datetime handling
# ============================================================

REST_FRAMEWORK = {

    # Authentication mechanism for APIs
    "DEFAULT_AUTHENTICATION_CLASSES": (

        # Enables JWT token authentication
        "rest_framework_simplejwt.authentication.JWTAuthentication",

        # Uncomment if session-based login is required
        # "rest_framework.authentication.SessionAuthentication",
    ),

    # Default permission for all APIs
    # User must be authenticated unless overridden in view
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    # Output datetime format in API responses
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S %Z",

    # Accepted input datetime formats
    "DATETIME_INPUT_FORMATS": [
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M",
        "iso-8601",
    ],
}


# ============================================================
# SIMPLE JWT CONFIGURATION
# Controls token lifetime & behavior
# ============================================================

SIMPLE_JWT = {

    # How long access token is valid
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=6),

    # How long refresh token is valid
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),

    # Issue new refresh token on refresh
    "ROTATE_REFRESH_TOKENS": True,

    # Blacklist old refresh token after rotation
    "BLACKLIST_AFTER_ROTATION": True,

    # Token prefix in Authorization header
    # Example: Authorization: Bearer <token>
    "AUTH_HEADER_TYPES": ("Bearer",),

    # Token class used for authentication
    "AUTH_TOKEN_CLASSES": (
        "rest_framework_simplejwt.tokens.AccessToken",
    ),
}


# ============================================================
# SWAGGER (DRF-YASG) CONFIGURATION
# Controls API documentation & authorization
# ============================================================

SWAGGER_SETTINGS = {

    # Define JWT authorization mechanism in Swagger UI
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header using: Bearer <token>",
        }
    },

    # Root API info object
    "DEFAULT_INFO": "Backend.urls.api_info",

    # Disable Django session authentication inside Swagger
    "USE_SESSION_AUTH": False,

    # Make Bearer token required globally
    "SECURITY_REQUIREMENTS": [{"Bearer": []}],
}


AZURE_EMAIL = {
    "TENANT_ID": config.get("AZURE", "TENANT_ID"),
    "CLIENT_ID": config.get("AZURE", "CLIENT_ID"),
    "CLIENT_SECRET": config.get("AZURE", "CLIENT_SECRET"),
    "EMAIL_ACCOUNT": config.get("AZURE", "EMAIL_ACCOUNT"),
}

EMAILS = {
    "MARKETING":  config.get("EMAIL_IDS", "MARKETING"),
    "TQM": config.get("EMAIL_IDS", "TQM"),
    "PURCHASE": config.get("EMAIL_IDS", "PURCHASE"),
    "WAREHOUSE": config.get("EMAIL_IDS", "WAREHOUSE"),
}

    
