# Generated by Django 5.2.11 on 2026-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPSampleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_sale_order_no', models.CharField(max_length=255, unique=True)),
                ('existing_customer', models.BooleanField(default=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('sale_order_number', models.CharField(max_length=255)),
                ('ppc_sample_requirement_date', models.DateField(blank=True, null=True)),
                ('top_sample_requirement_date', models.DateField(blank=True, null=True)),
                ('testing_requirement_date', models.DateField(blank=True, null=True)),
                ('adv_photoshoot_requirement_date', models.DateField(blank=True, null=True)),
                ('anyother_requirement_date', models.DateField(blank=True, null=True)),
                ('ppc_actual_requirement_date', models.DateField(blank=True, null=True)),
                ('top_actual_requirement_date', models.DateField(blank=True, null=True)),
                ('testing_actual_requirement_date', models.DateField(blank=True, null=True)),
                ('adv_photoshoot_actual_requirement_date', models.DateField(blank=True, null=True)),
                ('anyother_actual_requirement_date', models.DateField(blank=True, null=True)),
                ('top_required', models.BooleanField(default=False)),
                ('testing_required', models.BooleanField(default=False)),
                ('pp_required', models.BooleanField(default=False)),
                ('adv_photoshoot_required', models.BooleanField(default=False)),
                ('anyother_requirement', models.TextField(blank=True, null=True)),
                ('pp_remarks', models.TextField(blank=True, null=True)),
                ('top_remarks', models.TextField(blank=True, null=True)),
                ('testing_remarks', models.TextField(blank=True, null=True)),
                ('adv_photoshoot_remarks', models.TextField(blank=True, null=True)),
                ('anyother_remarks', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('no_of_samples', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'pp_sample_order',
                'ordering': ['-created_on'],
            },
        ),
    ]
