# Generated by Django 5.2.11 on 2026-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabDipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SOLID_TOWEL', 'Solid Towel'), ('YD_JQ_TOWEL', 'YD JQ Towel'), ('TERRY_TT', 'Terry TT'), ('RUGS', 'Rugs')], max_length=50)),
                ('no_of_shade', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('enquiry', models.CharField(blank=True, max_length=255, null=True)),
                ('design_name', models.CharField(blank=True, max_length=255, null=True)),
                ('greige_mat_code', models.CharField(blank=True, max_length=255, null=True)),
                ('towel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('yarn_type', models.CharField(blank=True, max_length=255, null=True)),
                ('border_type', models.CharField(blank=True, max_length=255, null=True)),
                ('mix_match', models.BooleanField(default=False)),
                ('light_source', models.CharField(blank=True, max_length=255, null=True)),
                ('party_protocol_attached', models.BooleanField(default=False)),
                ('shade_match_with', models.CharField(blank=True, max_length=255, null=True)),
                ('approval', models.CharField(blank=True, max_length=255, null=True)),
                ('special_features', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'labdip_request',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LabDipRugsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=255)),
                ('standard_type', models.CharField(max_length=255)),
                ('material_description', models.TextField()),
                ('piece_dyeing', models.CharField(max_length=255)),
                ('yarn_dyeing', models.CharField(max_length=255)),
                ('product_route_quality', models.CharField(max_length=255)),
                ('coordinate_with_towel', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'labdip_rugs_details',
            },
        ),
        migrations.CreateModel(
            name='LabDipShade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade_name', models.CharField(max_length=255)),
                ('archroma_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pantone_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('shade_details', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'labdip_shades',
            },
        ),
        migrations.CreateModel(
            name='LabDipTerryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=255)),
                ('washing_type', models.CharField(max_length=255)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('lab_dip_status', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_dip_format', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'labdip_terry_details',
            },
        ),
    ]
