# Generated by Django 5.2.11 on 2026-04-28 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labdip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labdiprequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labdip_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labdiprequest',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labdip_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labdiprugsdetails',
            name='labdip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rugs_details', to='labdip.labdiprequest'),
        ),
        migrations.AddField(
            model_name='labdipshade',
            name='labdip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shades', to='labdip.labdiprequest'),
        ),
        migrations.AddField(
            model_name='labdipterrydetails',
            name='labdip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terry_details', to='labdip.labdiprequest'),
        ),
    ]
