# Generated by Django 5.2.10 on 2026-08-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonprogram',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
