# Generated by Django 5.2.11 on 2026-03-16 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprogramstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityprogramstatus',
            name='purchase_sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_assigned_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityprogramstatus',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartonprogram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carton_program_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartonprogram',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carton_program_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedsheetprogramdetails',
            name='carton_program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedsheet_details', to='programs.cartonprogram'),
        ),
        migrations.AddField(
            model_name='bathrobeprogramdetails',
            name='carton_program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathrobe_details', to='programs.cartonprogram'),
        ),
        migrations.AddField(
            model_name='activityprogramstatus',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_statuses', to='programs.cartonprogram'),
        ),
        migrations.AddField(
            model_name='cartonprogramattachment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='programs.cartonprogram'),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='carton_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprograms', to='programs.cartonprogram'),
        ),
        migrations.AddField(
            model_name='gussetprogram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gusset_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gussetprogram',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gusset_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gussetprogramspecification',
            name='gusset_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_specifications', to='programs.gussetprogram'),
        ),
        migrations.AddField(
            model_name='gussetsampleprogram',
            name='gusset_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='programs.gussetprogram'),
        ),
        migrations.AddField(
            model_name='sampleprogram',
            name='carton_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_programs', to='programs.cartonprogram'),
        ),
        migrations.AddField(
            model_name='terrytowelprogramdetails',
            name='carton_program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terry_details', to='programs.cartonprogram'),
        ),
        migrations.AlterUniqueTogether(
            name='activityprogramstatus',
            unique_together={('activity', 'program')},
        ),
    ]
