# Generated by Django 5.2.10 on 2026-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_cartonprogram_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_cartons_per_20ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_cartons_per_40ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_cbm_per_carton',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_pallet_per_20ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_pallet_per_40ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_pdq_per_20ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='saved_pdq_per_40ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
