# Generated by Django 5.2.10 on 2026-08-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_cartonprogramsubprogram_saved_cartons_per_20ft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='is_recalculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='last_recalculated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
