# Generated by Django 5.2.10 on 2026-08-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_cartonprogramsubprogram_is_recalculated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='folded_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartonprogramsubprogram',
            name='folded_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
