# Generated by Django 5.2.11 on 2026-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(help_text='Module or screen name e.g. Carton Program, Activity Status', max_length=200)),
                ('record_id', models.CharField(help_text='Primary key of related record', max_length=100)),
                ('action', models.CharField(help_text='Created / Updated / Assigned / Status Changed / Deleted', max_length=100)),
                ('message', models.TextField(help_text='Human readable description of action')),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('performed_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('performed_by_role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_on'],
            },
        ),
    ]
