# Generated by Django 5.2.11 on 2026-04-28 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pp_sample', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ppsampleorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_sample_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ppsampleorder',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_sample_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
