# Generated by Django 5.2.10 on 2026-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MARKETING', 'Marketing'), ('TTQM', 'TTQM'), ('PURCHASE', 'PURCHASE'), ('SUPER_ADMIN', 'Super Admin'), ('EMPLOYEE', 'Employee')], db_index=True, default='EMPLOYEE', max_length=20),
        ),
    ]
