# Generated by Django 5.2.10 on 2026-02-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MARKETING', 'Marketing'), ('TTQM', 'TTQM'), ('PURCHASE', 'PURCHASE'), ('SUPER_ADMIN', 'Super Admin'), ('EMPLOYEE', 'Employee'), ('PPC', 'PPC'), ('WAREHOUSE', 'Warehouse')], db_index=True, default='EMPLOYEE', max_length=20),
        ),
    ]
