// Shared field definitions for the Bedsheet "Freezing Note" table.
// Used by FormMain.jsx (create), EditCartonForm.jsx (edit — Marketing only),
// and CartonView.jsx (read-only view for all roles).
// Keeping this in one place means all three UIs always stay in sync.

export const FREEZING_NOTE_FIELDS = [
  { key: 'sr_no', label: 'Sr. No.', type: 'number', width: 'w-16' },
  { key: 'buyer', label: 'Buyer', type: 'text', width: 'w-28' },
  { key: 'tc', label: 'TC', type: 'text', width: 'w-24' },
  { key: 'program', label: 'Program', type: 'text', width: 'w-32' },
  { key: 'date_of_carton_dimension_finalization', label: 'Date of Carton Dimension Finalization', type: 'date', width: 'w-36' },
  { key: 'product', label: 'Product', type: 'text', width: 'w-28' },
  { key: 'size', label: 'Size', type: 'text', width: 'w-24' },
  { key: 'product_dimension', label: 'Product Dimension (IN or CM)', type: 'text', width: 'w-40' },
  { key: 'pcs_per_bag_or_inner_box', label: 'Pcs/Bag or Pcs/Inner Box', type: 'text', width: 'w-28' },
  { key: 'bag_or_innerbox_per_carton', label: 'Bag/Inner Box per Carton', type: 'text', width: 'w-28' },
  { key: 'pcs_per_carton', label: 'Pcs/Carton', type: 'text', width: 'w-24' },
  { key: 'carton_type_paper', label: 'Carton Type (Outer/Inner) Paper', type: 'text', width: 'w-36' },
  { key: 'carton_length_cm', label: 'Carton Length (CM)', type: 'number', width: 'w-24' },
  { key: 'carton_width_cm', label: 'Carton Width (CM)', type: 'number', width: 'w-24' },
  { key: 'carton_height_cm', label: 'Carton Height (CM)', type: 'number', width: 'w-24' },
  { key: 'cbm', label: 'CBM (Auto)', type: 'readonly', width: 'w-24' },
  { key: 'max_outside_carton_dimension', label: 'Max Outside Carton Dim. (L+W+H)', type: 'readonly', width: 'w-28' },
  { key: 'net_weight_kgs', label: 'Net Weight (KGS)', type: 'number', width: 'w-24' },
  { key: 'gross_weight_kgs', label: 'Gross Weight (KGS)', type: 'number', width: 'w-24' },
  { key: 'carton_ply_no', label: 'Carton Ply No.', type: 'text', width: 'w-20' },
  { key: 'carton_min_bursting_strength', label: 'Min Bursting Strength (KG/SQ.CM)', type: 'text', width: 'w-32' },
  { key: 'carton_min_edge_crush_test', label: 'Min Edge Crush Test (LBS/INCH)', type: 'text', width: 'w-32' },
  { key: 'stiffener_dimension', label: 'Stiffener Dimension', type: 'text', width: 'w-40' },
  { key: 'stiffener_no_of_ply', label: 'Stiffener No. of Ply', type: 'text', width: 'w-20' },
  { key: 'stiffener_type_cut', label: 'Stiffener Type & Cut', type: 'text', width: 'w-32' },
  { key: 'side_stiffener_dimension', label: 'Side Stiffener Dimension', type: 'text', width: 'w-40' },
  { key: 'side_stiffener_no_of_ply', label: 'Side Stiffener No. of Ply', type: 'text', width: 'w-20' },
  { key: 'side_stiffener_type_cut', label: 'Side Stiffener Type & Cut', type: 'text', width: 'w-32' },
  { key: 'separator_dimension', label: 'Separator Dimension', type: 'text', width: 'w-32' },
  { key: 'separator_no_of_ply', label: 'Separator No. of Ply', type: 'text', width: 'w-20' },
  { key: 'bag_or_innerbox_size', label: 'Bag/Inner Box Size', type: 'text', width: 'w-32' },
  { key: 'bag_type_or_box_type', label: 'Bag Type / Box Type', type: 'text', width: 'w-28' },
  { key: 'ld_polybag_length_cm', label: 'LD Polybag Length (CM)', type: 'number', width: 'w-24' },
  { key: 'ld_polybag_width_cm', label: 'LD Polybag Width (CM)', type: 'number', width: 'w-24' },
  { key: 'ld_polybag_flap_cm', label: 'LD Polybag Flap (CM)', type: 'number', width: 'w-24' },
  { key: 'ld_polybag_thickness_micron', label: 'LD Polybag Thickness (Micron)', type: 'text', width: 'w-28' },
  { key: 'ld_polybag_quality', label: 'LD Polybag Quality', type: 'text', width: 'w-24' },
  { key: 'printing_matter_polybag', label: 'Printing Matter on Polybag', type: 'textarea', width: 'w-56' },
  { key: 'product_position_in_carton', label: 'Product Position in Carton', type: 'text', width: 'w-32' },
  { key: 'folded_product_length', label: 'Folded Product Length', type: 'text', width: 'w-24' },
  { key: 'folded_product_width', label: 'Folded Product Width', type: 'text', width: 'w-24' },
  { key: 'folded_product_height', label: 'Folded Product Height', type: 'text', width: 'w-24' },
  { key: 'bellyband_ribbon_dimension', label: 'Bellyband/Ribbon Dimension', type: 'text', width: 'w-32' },
  { key: 'bellyband_ribbon_quality', label: 'Bellyband/Ribbon Quality', type: 'text', width: 'w-28' },
  { key: 'macys_tmcl_placement', label: "Macy's TMCL Placement", type: 'text', width: 'w-28' },
  { key: 'macys_carton_type', label: "Macy's Carton Type", type: 'text', width: 'w-28' },
  { key: 'macys_tmcl_placement_type', label: "Macy's TMCL Placement Type", type: 'text', width: 'w-28' },
  { key: 'pdq_accessories_others', label: 'PDQ Accessories & Others', type: 'text', width: 'w-32' },
  { key: 'remarks', label: 'Remarks', type: 'textarea', width: 'w-40' },
];